name: ENV
description: Prepare the environment

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: true

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
